/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hackToolkit */

#ifndef _Included_hackToolkit
#define _Included_hackToolkit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hackToolkit
 * Method:    nicePing
 * Signature: (Ljava/lang/String;Ljava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_hackit_hackToolkit_nicePing
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     hackToolkit
 * Method:    loopPing
 * Signature: (Ljava/lang/String;Ljava/lang/String;[BJ)V
 */
JNIEXPORT void JNICALL Java_hackit_hackToolkit_loopPing
  (JNIEnv *, jobject, jstring, jstring, jstring, jlong);

/*
 * Class:     hackToolkit
 * Method:    pingOfDeath
 * Signature: (Ljava/lang/String;Ljava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_hackit_hackToolkit_pingOfDeath
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif